[[pages]]
path = "/"
screenshotTimestamp = "2026-04-29T06:42:05Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/da035652-6395-4b6a-a161-1bd85efb2a0e/2bab499d-a591-487a-870a-79d0ea401360/WvEm3Ph"

[[pages]]
path = "/bias-monitor"
screenshotTimestamp = "2026-04-29T06:43:06Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/da035652-6395-4b6a-a161-1bd85efb2a0e/2bab499d-a591-487a-870a-79d0ea401360/aoiPnKj"
